Add option not to keep separator
sotte/presenting.nvim pull request #10
Opened 2024-10-21 23:47 UTC by gerazov

Great plugin! I've been looking for a Neovim native slideshow for a while ...

Switching from `lookatme` and `slides` to `presenting.nvim` by not keeping the `---` separator allows me to use the same file with the three. 

In addition, the option not to keep the separator makes it easier to organize slides with multiple headings in them.

2024-10-27 10:08 UTC, sotte requested changes
Thanks for the PR!  This is a nice addition.

I left some small suggestions.

2024-10-27 10:08 UTC, sotte commented on lua/presenting/init.lua
> +    width = 90,
Please undo changing the default config.

2024-10-27 10:08 UTC, sotte commented on lua/presenting/init.lua
> +    ["L"] = function() Presenting.last() end,
Please undo changing the default config.

2024-10-27 10:08 UTC, sotte commented on lua/presenting/init.lua
> +  keep_separator = true,
Please also document this behavior, so that it appears in the helptext. Maybe even mention your use case.

2024-10-28 08:06 UTC, gerazov commented
ok done. My config got pushed by mistake :sweat_smile: 

Although I think that remapping `l` is not very useful - because it doesn't allow you to move around the text while you're presenting.

2024-11-03 19:25 UTC, sotte approved these changes

2024-11-03 19:31 UTC, sotte commented
Thank you so much for the PR. I fixed then linting issues and merged it.

> Although I think that remapping l is not very useful - because it doesn't allow you to move around the text while you're presenting.

Of course you're right. I have a nav layer on my keyboard that I use everywhere including in vim, so I didn't even notice that.

2024-11-03 19:32 UTC, closed without merging